"""Run every query in sql/analysis/ against the warehouse and record results.

    python src/analyze.py

Writes one CSV per query into outputs/results/ plus a combined ANALYSIS.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import duckdb  # noqa: E402

from config import ANALYSIS_SQL_DIR, RESULTS_DIR, WAREHOUSE  # noqa: E402

PREVIEW_ROWS = {"02_demand_by_hour_dow": 12, "03_borough_flows": 15,
                "07_top_zones": 15}
DEFAULT_PREVIEW = 25


def main() -> None:
    if not WAREHOUSE.exists():
        raise SystemExit("Warehouse missing. Run: python src/pipeline.py")

    con = duckdb.connect(str(WAREHOUSE), read_only=True)
    files = sorted(ANALYSIS_SQL_DIR.glob("*.sql"))
    if not files:
        raise SystemExit(f"No .sql files in {ANALYSIS_SQL_DIR}")

    md = [
        "# NYC taxi analysis results\n",
        "Generated by `src/analyze.py` against the warehouse built by "
        "`src/pipeline.py`. Each section is the output of the correspondingly "
        "named file in `sql/analysis/`.\n",
    ]

    for path in files:
        header = [ln.lstrip("- ").strip() for ln in path.read_text(encoding="utf-8").splitlines()
                  if ln.strip().startswith("--")]
        title = header[0] if header else path.stem
        blurb = " ".join(header[1:]) if len(header) > 1 else ""

        df = con.execute(path.read_text(encoding="utf-8")).fetchdf()
        out = RESULTS_DIR / f"{path.stem}.csv"
        df.to_csv(out, index=False)
        print(f"  {path.stem:<32} {len(df):>6,} rows -> {out.name}")

        n = PREVIEW_ROWS.get(path.stem, DEFAULT_PREVIEW)
        md.append(f"\n## {title}\n")
        if blurb:
            md.append(f"_{blurb}_\n")
        md.append(f"\n`{len(df):,} rows` — full output in [`{out.name}`]({out.name})\n")
        md.append("\n" + df.head(n).to_markdown(index=False) + "\n")
        if len(df) > n:
            md.append(f"\n_...{len(df)-n:,} further rows in the CSV._\n")

    con.close()
    summary = RESULTS_DIR / "ANALYSIS.md"
    summary.write_text("".join(md), encoding="utf-8")
    print(f"\nWrote {summary}")


if __name__ == "__main__":
    main()
